In [1]:
import math

def sigmoid_fun(x):
    s=1/(1+math.exp(-x))
    return s
val=sigmoid_fun(-1)
print(val)

0.2689414213699951


In [2]:
import numpy as np
arr=[1,2,3]
x= np.array(arr)
print(np.exp(x))

[ 2.71828183  7.3890561  20.08553692]


In [3]:
#elementary functions are implemented to check if the operations are done right or not
print(x+3)

[4 5 6]


In [4]:
def sigmoid_fun_np(x):
    s=1/(1+np.exp(-x))
    grad=s*(1-s)
    return grad
val=sigmoid_fun_np(x)
print(val)

[0.19661193 0.10499359 0.04517666]


In [5]:
import random
#flattening of an image (length*height*3,1)
image=np.random.uniform(2, size=(3,3,2)) 
print(image)

[[[1.78013947 1.7094252 ]
  [1.2663808  1.31121303]
  [1.41391543 1.13881251]]

 [[1.31094844 1.56374977]
  [1.00108402 1.27506591]
  [1.25986558 1.66151941]]

 [[1.54499868 1.51025605]
  [1.27823094 1.74926522]
  [1.83309091 1.28856163]]]


In [6]:
#reshaping of the image
image_reshaped=image.reshape(3*2*3,1)
print(image_reshaped)

[[1.78013947]
 [1.7094252 ]
 [1.2663808 ]
 [1.31121303]
 [1.41391543]
 [1.13881251]
 [1.31094844]
 [1.56374977]
 [1.00108402]
 [1.27506591]
 [1.25986558]
 [1.66151941]
 [1.54499868]
 [1.51025605]
 [1.27823094]
 [1.74926522]
 [1.83309091]
 [1.28856163]]


In [8]:
def normalize(x):
    norm=np.linalg.norm(x,axis=1,keepdims=True)
    l=x/norm
    return l

a=[0,1000,4],[2,6,4]
array=np.array(a)
val=normalize(a)
print(val)


[[0.         0.999992   0.00399997]
 [0.26726124 0.80178373 0.53452248]]


In [19]:
def softmax(x):
    x_exp = np.exp(x)
    
    x_sum = np.sum(x_exp, axis = 1, keepdims = True)
    
    x = x_exp/x_sum
    
    return x

img_input = np.array([[9,2,5,0,0],
                [7,5,0,0,0]])
img_input = softmax(img_input)
img_input

array([[9.80897665e-01, 8.94462891e-04, 1.79657674e-02, 1.21052389e-04,
        1.21052389e-04],
       [8.78679856e-01, 1.18916387e-01, 8.01252314e-04, 8.01252314e-04,
        8.01252314e-04]])

In [24]:
import time
s1=np.random.rand(1000000)
s2=np.random.rand(1000000)

tic=time.process_time()
dot=0
for i in range(len(s1)):
    dot+=s1[i]*s2[i]
    
toc=time.process_time()
print("dot = "+str(dot)+"\nComputation Time:" + str(1000*(toc-tic))+"ms")

dot = 250330.90500746598
Computation Time:62.5ms


In [25]:
import time
s1=np.random.rand(1000000)
s2=np.random.rand(1000000)

tic=time.process_time()
np.dot(s1, s2)
for i in range(len(s1)):
    dot+=s1[i]*s2[i]
    
toc=time.process_time()
print("dot = "+str(dot)+"\nComputation Time:" + str(1000*(toc-tic))+"ms")

dot = 500470.0391457319
Computation Time:109.375ms
